[package]
name = "t-rex"
version = "0.0.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[features]
dbtest = []

[dependencies]
toml = "*"
postgis = "*"
openssl = "*"
protobuf = "*"
nickel = "*"
nickel_mustache = "*"
rustc-serialize = "*"
clap = "*"
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"

[dependencies.postgres]
version = "*"
features = ["openssl"]
#Breaks Windows build
#features = ["unix_socket"]

[dependencies.hyper]
version = "0.8.1"
default-features = false
